# Generated by Django 2.2.28 on 2024-11-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241113_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='origine',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='sport',
        ),
    ]
